server:
  sv_allow_origins: *
  sv_allow_methods: GET, POST, PUT, DELETE
  sv_allow_headers: content-type
  sv_content_type: application/json
database:
  db_host: db
  db_port: 3306
  db_user: dev
  db_password: 123456
  db_name: pp3_p3_db
states_machine: 
  states: void, preinscription_on_proc, preinscript, preinscription_in_list, inscript, annulled, annulled_inscript
state_machine_transitions:
  void: preinscription_on_proc
  preinscription_on_proc: preinscript, preinscription_in_list, annulled
  preinscript: inscript, preinscription_in_list, annulled
  preinscription_in_list: inscript, annulled
  inscript: preinscription_in_list, annulled, annulled_inscript